name: Archive Private Repos to Azure

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 5"   # Runs at 03:00, only on Friday.
  workflow_call:
    secrets:
      ARCHIVE_APP_ID:
        required: true
      ARCHIVE_APP_PRIVATE_KEY:
        required: true
      AZURE_STORAGE_KEY:
        required: true

jobs:
  archive:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Az PowerShell modules
        run: |
          Install-Module -Name Az.Accounts -Force -Scope CurrentUser
          Install-Module -Name Az.Storage -Force -Scope CurrentUser

      - name: Verify Azure Resources
        run: |
          $ErrorActionPreference = "Stop"
          
          $storageAccount = "${{ vars.AZURE_STORAGE_ACCOUNT }}"
          $containerName = "${{ vars.CONTAINER_NAME }}"
          
          if ([string]::IsNullOrEmpty($storageAccount)) {
            Write-Error "Storage account name is not set. Please check GitHub repository variables."
            exit 1
          }
          
          if ([string]::IsNullOrEmpty($containerName)) {
            Write-Error "Container name is not set. Please check GitHub repository variables."
            exit 1
          }
          
          $connectionString = "DefaultEndpointsProtocol=https;AccountName=$storageAccount;AccountKey=${{ secrets.AZURE_STORAGE_KEY }};EndpointSuffix=core.windows.net"
          $ctx = New-AzStorageContext -ConnectionString $connectionString
          
          try {
            Get-AzStorageContainer -Name $containerName -Context $ctx | Out-Null
            Write-Host "✅ Azure resources verified successfully."
          } catch {
            Write-Error "Failed to access container '$containerName' in storage account '$storageAccount'. Please ensure the Terraform deployment has been run successfully."
            exit 1
          }

      - name: Create Token
        id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.ARCHIVE_APP_ID }}
          private_key: ${{ secrets.ARCHIVE_APP_PRIVATE_KEY }}

      - name: Archive selected private repos
        run: |
          pwsh ./archive-private-repos.ps1 `
            -GitHubOrg ${{ vars.GIT_HUB_ORG }} `
            -GitHubToken ${{ steps.create_token.outputs.token }} `
            -StorageAccountName ${{ vars.AZURE_STORAGE_ACCOUNT }} `
            -StorageAccountKey ${{ secrets.AZURE_STORAGE_KEY }} `
            -ContainerName ${{ vars.CONTAINER_NAME }} `
            -RetentionDays 60
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
